In [1]:
import numpy as np

# Pair Numpy

## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
array_aleatoria = np.random.randint(10, 100, 50)

array_accede = array_aleatoria[::5]

print(array_aleatoria)
print(array_accede)

[72 84 86 59 63 93 46 68 52 82 39 17 57 38 43 58 50 55 76 46 68 35 72 27
 75 47 70 96 90 91 64 40 32 55 77 97 48 43 56 69 12 67 73 30 40 56 45 92
 70 41]
[72 93 39 58 68 47 64 97 12 56]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [3]:
lista_1d = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

array_1d = np.array(lista_1d)

print(array_1d)
print(array_1d[::2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [4]:
array_2d = np.random.rand(4, 6) + 10 # Al sumarle un numero mayor de 1 ya se cumple la condición asegurandonos que no estén los decimales comprendidos entre 0 y 1
array_2d = np.round(array_2d, 2)
ultima_fila = array_2d[-1, :]
print(array_2d)
print("\n -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-\n ")
print(f"La última fila es: {ultima_fila}")

[[10.76 10.63 10.46 10.63 10.21 10.35]
 [10.33 10.75 10.19 10.88 10.98 10.21]
 [10.04 10.85 10.06 10.6  11.   10.91]
 [10.53 10.03 10.27 10.32 10.8  10.08]]

 -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
 
La última fila es: [10.53 10.03 10.27 10.32 10.8  10.08]


4. **BONUS:** Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [5]:
array_3d = np.random.randint(0, 101, (2, 3, 5))
print(array_3d)
print("-----------------------")
array_3d[array_3d % 3 == 0] = 0  # Si el resto de la división es 0, es múltiple de tres, por lo tanto se evalúa como True y es reemplazado. 
print(f"Array con elementos reemplazados: {array_3d}")

[[[77 75 28 81 95]
  [52 47 72 63 32]
  [21 87 64 84 31]]

 [[48 44 23 80 99]
  [46 27 50 64 83]
  [79 19 68 33  0]]]
-----------------------
Array con elementos reemplazados: [[[77  0 28  0 95]
  [52 47  0  0 32]
  [ 0  0 64  0 31]]

 [[ 0 44 23 80  0]
  [46  0 50 64 83]
  [79 19 68  0  0]]]


## Reshape y Transpose:

### Ejercicios con reshape:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [6]:
array_2x3x4 = np.random.randint(1, 101, (2, 3, 4))
print(array_2x3x4)
array2x3x4_2d = array_2x3x4.reshape(6, 4) # Para que funcionara el reshape y que contuviera todos los numeros, le he indicado que me de 6 filas que es la suma de las 3 del array 3d.
print(array2x3x4_2d)

[[[15 81  5 17]
  [ 3 75 79  2]
  [11 14 56 90]]

 [[42 30 65 87]
  [60 47 61  3]
  [20 81 90 52]]]
[[15 81  5 17]
 [ 3 75 79  2]
 [11 14 56 90]
 [42 30 65 87]
 [60 47 61  3]
 [20 81 90 52]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [7]:
array_3d = np.arange(1, 61).reshape((3, 4, 5))
print(array_3d)
print("----------------------")

array_2d = array_3d.reshape((3*4, 5))
print(array_2d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
----------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


### Ejercicios con transpose:

3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [8]:
permutada = array_3d.transpose(2, 1, 0)
print(permutada)

[[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]



4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [9]:
array_3d = np.arange(1, 61).reshape((3, 4, 5))
print(array_3d)
print("--------------------")
array_transposed = array_3d.transpose((0, 2, 1))
print(array_transposed)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
--------------------
[[[ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]
  [ 5 10 15 20]]

 [[21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]
  [25 30 35 40]]

 [[41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]
  [45 50 55 60]]]


### Preguntas teóricas:

5. ¿Qué diferencia existe entre el reshape y el transpose?
El RESHAPE cambia la forma del array sin modificar sus datos y el TRANSPOSE cambia el orden de los ejes del array

6. ¿Y entre el transpose y el swapaxes?

El método TRANSPOSE permite reorganizar todos los ejes según un nuevo orden especificado, mientras que SWAPAXES solo intercambia 2 ejes concretos.

## Funciones Aritméticas y Estadísticas:

1. Crea un array de 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [10]:
d3 = np.random.rand(2, 3, 5)
d3_redondeado = np.round(d3, 1)
print(d3_redondeado)

[[[0.1 0.5 0.4 0.6 0.7]
  [0.3 0.1 0.8 1.  0.2]
  [0.6 0.6 0.5 0.1 0.7]]

 [[0.9 0.4 0.2 0.9 0.7]
  [0.3 0.5 0.5 0.3 0.5]
  [0.  0.6 1.  0.9 0.4]]]



2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".

- Si el valor del array es mayor que la media, se reemplaza por "B".

- Si el valor del array es menor que la media, se reemplaza por "C".

- Si el valor es igual que el máximo, se reemplaza por "D".

- Si el valor es igual que el mínimo, se reemplaza por "E".