In [6]:
import pandas as pd
import random
import numpy as np

1. ¿Qué diferencia hay entre una Serie y un DataFrame?

- La serie es unidimensional y puede contener cualquier tipo de datos mientras sean los mismos. 
- El Dataframe es bidimensional y sus columnas pueden contener diferentes tipos de datos. 
- Dataframes tienen índices para sus filas y columnas. 
- Series tienen etiquetas. 

## SERIES 
2. Crea dos listas:  
- Una que se llame "valores" que tenga 7 números aleatorios.
- Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [13]:
valores = np.random.randint(1,100,7)
print(valores)
indices = ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"]
print(indices)


[29 35 82 73 34 33  7]
['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']


- A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [14]:
serie = pd.Series(valores, index=indices)
print(serie)

Lunes        29
Martes       35
Miercoles    82
Jueves       73
Viernes      34
Sabado       33
Domingo       7
dtype: int64


- A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez.

In [19]:
diccionario = {}
for indice, valor in zip(indices,valores):
    diccionario[indice] = valor

print(diccionario)
# Forma para no ver el tipo de dato (int64) en el resultado: aplicar int.
diccionario1 = {indice: int(valor) for indice, valor in zip(indices, valores)}
print (diccionario1)

{'Lunes': np.int64(29), 'Martes': np.int64(35), 'Miercoles': np.int64(82), 'Jueves': np.int64(73), 'Viernes': np.int64(34), 'Sabado': np.int64(33), 'Domingo': np.int64(7)}
{'Lunes': 29, 'Martes': 35, 'Miercoles': 82, 'Jueves': 73, 'Viernes': 34, 'Sabado': 33, 'Domingo': 7}


- Crea una Serie con el diccionario creado en el punto anterior.

In [21]:
serie_dic = pd.Series(diccionario)
serie_dic

Lunes        29
Martes       35
Miercoles    82
Jueves       73
Viernes      34
Sabado       33
Domingo       7
dtype: int64

- ¿Qué forma tiene esta última Serie?

- ¿Qué tipo de datos tiene?

- ¿Qué tamaño tiene?

- ¿Cuáles son los índices de la Serie?

- ¿Y los values?

In [27]:
forma_dic = serie_dic.shape
print(forma_dic)

tipo_dic = serie_dic.dtype
print(tipo_dic)

tamaño_dic = serie_dic.size
print(tamaño_dic)

valores_dic = serie_dic.values
print(valores_dic)


(7,)
int64
7
[29 35 82 73 34 33  7]


- Extrae el valor para el índice "lunes"

- Extrae el valor para el índice "lunes", "martes" y "miércoles".

- Extrae el valor para el índice "lunes" y "domingo".

In [38]:
valor_lunes_dic = serie_dic.loc['Lunes']
print(valor_lunes_dic)


valor_3dias_dic = serie_dic.loc[['Lunes', 'Martes', 'Miercoles']]
print(valor_3dias_dic)


valor_2dias_dic = serie_dic.loc[['Lunes', 'Domingo']]
print(valor_2dias_dic)

# Probamos el método iloc
valor_2dias_dic = serie_dic.iloc[[0, -1]]
print(valor_2dias_dic)

29
Lunes        29
Martes       35
Miercoles    82
dtype: int64
Lunes      29
Domingo     7
dtype: int64
Lunes      29
Domingo     7
dtype: int64


# DATAFRAMES

3. Crea un array de dos dimensiones con 4 filas y 3 columnas.
- Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [40]:
array_2d = np.random.randint(1,100,size=(4,3))
array_2d

array([[55, 75, 40],
       [99, 21, 28],
       [37, 37, 77],
       [42, 75, 61]])

In [41]:
df_2d = pd.DataFrame(array_2d, columns =["España", "Francia", "Italia"])
df_2d

España  Francia  Italia
0      55       75      40
1      99       21      28
2      37       37      77
3      42       75      61

Descarga el archivo "medallas" y carga el DataFrame.
- Usando el loc extrae todas las columnas de la fila de Tailandia.

- Usando el loc extrae todas las columnas de China e Irán.

- Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

- Usando el iloc extrae la información de la India. Devolved todas las columnas.

- Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

Contesta a las siguientes preguntas:

- ¿Qué país consiguió más de 200 medallas de oro?

- ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

- ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.