In [2]:
import numpy as np

# Pair Numpy

## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [3]:
array_aleatoria = np.random.randint(10, 100, 50)

array_accede = array_aleatoria[::5]

print(array_aleatoria)
print(array_accede)

[91 12 99 57 29 78 68 49 61 16 58 22 56 25 64 35 15 37 95 74 21 27 72 30
 27 34 29 44 59 52 24 36 44 75 64 81 87 94 17 39 36 53 32 84 51 36 53 12
 67 87]
[91 78 58 35 21 34 24 81 36 36]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [4]:
lista_1d = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

array_1d = np.array(lista_1d)

print(array_1d)
print(array_1d[::2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [5]:
array_2d = np.random.rand(4, 6) + 10 # Al sumarle un numero mayor de 1 ya se cumple la condición asegurandonos que no estén los decimales comprendidos entre 0 y 1
array_2d = np.round(array_2d, 2)
ultima_fila = array_2d[-1, :]
print(array_2d)
print("\n -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-\n ")
print(f"La última fila es: {ultima_fila}")

[[10.5  10.12 10.52 10.92 10.95 10.81]
 [10.83 10.51 10.49 10.04 10.49 10.64]
 [10.76 10.73 10.02 10.98 10.67 10.73]
 [10.54 10.83 10.85 10.27 10.37 10.16]]

 -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
 
La última fila es: [10.54 10.83 10.85 10.27 10.37 10.16]


4. **BONUS:** Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [6]:
array_3d = np.random.randint(0, 101, (2, 3, 5))
print(array_3d)
print("-----------------------")
array_3d[array_3d % 3 == 0] = 0  # Si el resto de la división es 0, es múltiple de tres, por lo tanto se evalúa como True y es reemplazado. 
print(f"Array con elementos reemplazados: {array_3d}")

[[[ 12  64  93  73  60]
  [ 59  26  25  45  23]
  [ 78  31  48  93  78]]

 [[ 72  28  92 100  15]
  [ 61  22  52  82  93]
  [ 20  84  25   3  58]]]
-----------------------
Array con elementos reemplazados: [[[  0  64   0  73   0]
  [ 59  26  25   0  23]
  [  0  31   0   0   0]]

 [[  0  28  92 100   0]
  [ 61  22  52  82   0]
  [ 20   0  25   0  58]]]


## Reshape y Transpose:

### Ejercicios con reshape:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [7]:
array_2x3x4 = np.random.randint(1, 101, (2, 3, 4))
print(array_2x3x4)
array2x3x4_2d = array_2x3x4.reshape(6, 4) # Para que funcionara el reshape y que contuviera todos los numeros, le he indicado que me de 6 filas que es la suma de las 3 del array 3d.
print(array2x3x4_2d)

[[[38 50  9 13]
  [36  3 46 11]
  [12 11 83  7]]

 [[ 9 47  6 48]
  [66 97 43 17]
  [95 25 45 69]]]
[[38 50  9 13]
 [36  3 46 11]
 [12 11 83  7]
 [ 9 47  6 48]
 [66 97 43 17]
 [95 25 45 69]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [8]:
array_3d = np.arange(1, 61).reshape((3, 4, 5))
print(array_3d)
print("----------------------")

array_2d = array_3d.reshape((3*4, 5))
print(array_2d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
----------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


### Ejercicios con transpose:

3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [9]:
permutada = array_3d.transpose(2, 1, 0)
print(permutada)

[[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]



4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [10]:
array_3d = np.arange(1, 61).reshape((3, 4, 5))
print(array_3d)
print("--------------------")
array_transposed = array_3d.transpose((0, 2, 1))
print(array_transposed)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
--------------------
[[[ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]
  [ 5 10 15 20]]

 [[21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]
  [25 30 35 40]]

 [[41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]
  [45 50 55 60]]]


### Preguntas teóricas:

5. ¿Qué diferencia existe entre el reshape y el transpose?
El RESHAPE cambia la forma del array sin modificar sus datos y el TRANSPOSE cambia el orden de los ejes del array

6. ¿Y entre el transpose y el swapaxes?

El método TRANSPOSE permite reorganizar todos los ejes según un nuevo orden especificado, mientras que SWAPAXES solo intercambia 2 ejes concretos.

## Funciones Aritméticas y Estadísticas:

1. Crea un array de 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [11]:
d3 = np.random.rand(2, 3, 5)
d3_redondeado = np.round(d3, 1)
print(d3_redondeado)

[[[0.4 0.9 0.7 0.7 0.6]
  [0.2 0.5 0.9 0.2 0.8]
  [0.8 0.5 0.2 0.2 0.9]]

 [[0.2 0.4 0.5 0.4 1. ]
  [0.9 0.9 0.9 0.8 0.7]
  [0.5 0.2 0.9 0.3 0.8]]]



2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".

- Si el valor del array es mayor que la media, se reemplaza por "B".

- Si el valor del array es menor que la media, se reemplaza por "C".

- Si el valor es igual que el máximo, se reemplaza por "D".

- Si el valor es igual que el mínimo, se reemplaza por "E".

In [28]:

media = np.mean(d3_redondeado)
maximo = np.max(d3_redondeado)
minimo = np.min(d3_redondeado)

print(media)
print(maximo)
print(minimo)

print("-------------------")

array_vacio = np.empty(d3_redondeado.shape, dtype=str)
print(array_vacio)


for i in range(d3_redondeado.shape[0]):
    for j in range(d3_redondeado.shape[1]):
        for k in range(d3_redondeado.shape[2]):
            valor = d3_redondeado[i, j, k]
            if valor == media:
                array_vacio[i, j, k] = 'A'
            elif valor == maximo:
                array_vacio[i, j, k] = 'D'
            elif valor == minimo:
                array_vacio[i, j, k] = 'E'
            elif valor > media:
                array_vacio[i, j, k] = 'B'
            else:
                array_vacio[i, j, k] = 'C'

print (f"El array transformado:\n {array_vacio}")


0.5966666666666666
1.0
0.2
-------------------
[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]
El array transformado:
 [[['C' 'B' 'B' 'B' 'B']
  ['E' 'C' 'B' 'E' 'B']
  ['B' 'C' 'E' 'E' 'B']]

 [['E' 'C' 'C' 'C' 'D']
  ['B' 'B' 'B' 'B' 'B']
  ['C' 'E' 'B' 'C' 'B']]]
