In [1]:
import pandas as pd
import random
import numpy as np

1. ¿Qué diferencia hay entre una Serie y un DataFrame?

- La serie es unidimensional y puede contener cualquier tipo de datos mientras sean los mismos. 
- El Dataframe es bidimensional y sus columnas pueden contener diferentes tipos de datos. 
- Dataframes tienen índices para sus filas y columnas. 
- Series tienen etiquetas. 

## SERIES 
2. Crea dos listas:  
- Una que se llame "valores" que tenga 7 números aleatorios.
- Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [2]:
valores = np.random.randint(1,100,7)
print(valores)
indices = ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"]
print(indices)


[45 68 37 54 18 65 82]
['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']


- A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [3]:
serie = pd.Series(valores, index=indices)
print(serie)

Lunes        45
Martes       68
Miercoles    37
Jueves       54
Viernes      18
Sabado       65
Domingo      82
dtype: int64


- A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez.

In [4]:
diccionario = {}
for indice, valor in zip(indices,valores):
    diccionario[indice] = valor

print(diccionario)
# Forma para no ver el tipo de dato (int64) en el resultado: aplicar int.
diccionario1 = {indice: int(valor) for indice, valor in zip(indices, valores)}
print (diccionario1)

{'Lunes': np.int64(45), 'Martes': np.int64(68), 'Miercoles': np.int64(37), 'Jueves': np.int64(54), 'Viernes': np.int64(18), 'Sabado': np.int64(65), 'Domingo': np.int64(82)}
{'Lunes': 45, 'Martes': 68, 'Miercoles': 37, 'Jueves': 54, 'Viernes': 18, 'Sabado': 65, 'Domingo': 82}


- Crea una Serie con el diccionario creado en el punto anterior.

In [5]:
serie_dic = pd.Series(diccionario)
serie_dic

Lunes        45
Martes       68
Miercoles    37
Jueves       54
Viernes      18
Sabado       65
Domingo      82
dtype: int64

- ¿Qué forma tiene esta última Serie?

- ¿Qué tipo de datos tiene?

- ¿Qué tamaño tiene?

- ¿Cuáles son los índices de la Serie?

- ¿Y los values?

In [6]:
forma_dic = serie_dic.shape
print(forma_dic)

tipo_dic = serie_dic.dtype
print(tipo_dic)

tamaño_dic = serie_dic.size
print(tamaño_dic)

valores_dic = serie_dic.values
print(valores_dic)


(7,)
int64
7
[45 68 37 54 18 65 82]


- Extrae el valor para el índice "lunes"

- Extrae el valor para el índice "lunes", "martes" y "miércoles".

- Extrae el valor para el índice "lunes" y "domingo".

In [7]:
valor_lunes_dic = serie_dic.loc['Lunes']
print(valor_lunes_dic)


valor_3dias_dic = serie_dic.loc[['Lunes', 'Martes', 'Miercoles']]
print(valor_3dias_dic)


valor_2dias_dic = serie_dic.loc[['Lunes', 'Domingo']]
print(valor_2dias_dic)

# Probamos el método iloc
valor_2dias_dic = serie_dic.iloc[[0, -1]]
print(valor_2dias_dic)

45
Lunes        45
Martes       68
Miercoles    37
dtype: int64
Lunes      45
Domingo    82
dtype: int64
Lunes      45
Domingo    82
dtype: int64


# DATAFRAMES

3. Crea un array de dos dimensiones con 4 filas y 3 columnas.
- Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [8]:
array_2d = np.random.randint(1,100,size=(4,3))
array_2d

array([[93, 92, 78],
       [82, 98, 12],
       [80, 99, 43],
       [14, 82, 72]])

In [9]:
df_2d = pd.DataFrame(array_2d, columns =["España", "Francia", "Italia"])
df_2d

España  Francia  Italia
0      93       92      78
1      82       98      12
2      80       99      43
3      14       82      72

Descarga el archivo "medallas" y carga el DataFrame.
- Usando el loc extrae todas las columnas de la fila de Tailandia.

- Usando el loc extrae todas las columnas de China e Irán.

- Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

- Usando el iloc extrae la información de la India. Devolved todas las columnas.

- Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

In [16]:
df = pd.read_csv("data/medallas.csv")
df

Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235

In [20]:
fila_tailandia=df.loc[df['País'] == 'Tailandia']
fila_tailandia

Unnamed: 0       País  Oro  Plata  Bronce
6           7  Tailandia  132    175     278

In [22]:
fila_china_iran = df.loc[df['País'].isin(['China', 'Irán'])]
fila_china_iran

Unnamed: 0   País   Oro  Plata  Bronce
0           1  China  1473    994     720
3           4   Irán   179    181     197

In [27]:
medallas_china_iran = df.loc[df['País'].isin(['China', 'Irán']), ['Oro', 'Plata', 'Bronce']]
medallas_china_iran

Oro  Plata  Bronce
0  1473    994     720
3   179    181     197

In [32]:
fila_india = df.iloc[5]
fila_india

Unnamed: 0        6
País          India
Oro             154
Plata           202
Bronce          315
Name: 5, dtype: object

In [33]:
paises_impares = df.iloc[1::2]
paises_impares

Unnamed: 0             País   Oro  Plata  Bronce
1           2            Japón  1032   1037     985
3           4             Irán   179    181     197
5           6            India   154    202     315
7           8        Indonesia   112    131     240
9          10  Corea del Norte    91    120     235

Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

Contesta a las siguientes preguntas:

- ¿Qué país consiguió más de 200 medallas de oro?

- ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

- ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.